### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by Chuxiaof** [miguelgrinberg/Flask-Moment#86]
I got the following error when importing `flask_moment`

```bash
$ flask run                    
 * Serving Flask app 'microblog.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'microblog', an ImportError was raised:

Traceback (most recent call last):
  File "/Users/fengchuxiao/Desktop/microblog/venv/lib/python3.8/site-packages/flask/cli.py", line 214, in locate_app
    __import__(module_name)
  File "/Users/fengchuxiao/Desktop/microblog/microblog.py", line 1, in <module>
    from app import app, db
  File "/Users/fengchuxiao/Desktop/microblog/app/__init__.py", line 8, in <module>
    from flask_moment import Moment
  File "/Users/fengchuxiao/Desktop/microblog/venv/lib/python3.8/site-packages/flask_moment/__init__.py", line 2, in <module>
    from packaging.version import parse as version_parse
ModuleNotFoundError: No module named 'packaging'
```

I worked around the issue by manually `pip install packaging`. I assume you forgot to specify `packaging` as a dependency? I am using `Flask-Moment==1.0.3`.

**Comment by miguelgrinberg** [comment]
Packaging is a dependency of setuptools, so I assumed it would always be installed.
